apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: test3-jan23-argo 
  janus-idp.io/tekton: test3-jan23-argo
  backstage.io/kubernetes-id: test3-jan23-argo
  backstage.io/kubernetes-namespace: rhdh-app 
  app.kubernetes.io/part-of: test3-jan23-argo
resources: 
- application-dev.yaml