apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: test3-jan23-argo
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jdubrick-ai/test3-jan23-argo:a5efb2a6371e9cb276a396c955f48d7e989ef4c1@sha256:ff313150f1feef73d43503409709814786c98b486b666d7ee4c3a72bf9201596 # use pre-built to bootstrap 
          name: app-inference
