apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: test3-jan23-argo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test3-jan23-argo 
  name: test3-jan23-argo
spec:
  port:
    targetPort: 8501
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: test3-jan23-argo 
    weight: 100 
  wildcardPolicy: None
